### ISSUE TITLE
Conflict with Enhanced Media Library PRO

### ISSUE THREAD

**Issue by jerturowetz** [xwp/wp-plugin-dependencies#48]
Strangely, turning Enhanced Media Library PRO on, stops this plugin from working completely.  It's not throwing back any errors; but I'll turn debug mode on and get back at ya.

**Comment by jrfnl** [comment]
Thanks for reporting.
Is this only with the PRO version or also with the free version ? And yes, more info would be much appreciated ;-)

**Comment by jerturowetz** [comment]
I'm preparing a slimmer copy of the install for you.  Gimme a few and I'll post details here.

**Comment by jerturowetz** [comment]
Here's a copy, pretty light (except for the wp submodule ;) )
https://bitbucket.org/JerTurowetz/plugin-deps-test

There's 4 files in the root which need to be renamed and configured to taste - should be obvious but pls fire any questions my way

**Comment by jrfnl** [comment]
@jerturowetz While I appreciate you trying to find the cause of the issue, this setup is not isolated enough to identify the issue (and I'm not looking to spend a day debugging a non-standard setup).

Please provide step-by-step details on how to reproduce the issue on a clean WP install.
If the issue cannot be reproduced on a clean WP install, the issue is with your setup, not with the plugin.

**Comment by jerturowetz** [comment]
Same urls - new files https://bitbucket.org/JerTurowetz/plugin-deps-test

This is the core wordpress install & 2 plugins (Enhanced Media Library PRO & wp-plugin-dependencies)

I set the default wordpress plugin 'hello' to rely on 'Askimet' - you'll notice when you turn Enhanced Media Library PRO on, the deps stop working

**Comment by jrfnl** [comment]
Ok, I haven't used your install - again, I only needed steps to isolate and replicate the issue.

I downloaded the EML Pro plugin and have found the issue. This is _their_ bug, not ours.

EML Pro is running some code related to the plugins list when the actual plugin file is loaded - i.e. not on a hook, let alone the correct hook -.
This prevents other plugins from hooking into the plugins list retrieval function.
The plugins list - including all plugin header information - is cached by WP within the retrieval function as the retrieval is an 'expensive' operation.
So when WPPD uses the same function later on, the cache is used and as the cache was created _before_ we could hook in, the additional information WPPD needs to display the dependencies is not available.

To fix this, open the file `wp-content/plugins/enhanced-media-library-pro/enhanced-media-library.php` and replace line 51 - 76 with the below code.

Take note of the following:
- I've change the inline code to a function
- and run it on the 'admin_init' hook (as you don't want to `die` with a informative message on the front-end anyway).

The functionality remains essentially the same, but now allows others a chance to hook in therefore not breaking other plugins.

All the same, this is not an ideal solution as the fact that this function is run on _every_ admin page (or originally on every page) is wrong by definition. The `get_plugins()` function as mentioned above is expensive and should only be run when _really_ needed.
The better solution would be to have a define or function in the free version of the plugin which doesn't exist or is different in the PRO version and to test for that in the function, rather than check the plugins list. This would also be more stable as now the existence of the free version is not detected if the user has renamed the plugin directory.
All the same, the code should even then still be run in `admin_init` and in a function and not in the global namespace.

To improve the function even more, they shouldn't use `die` there at all as that will prevent the user from getting to the plugins admin page easily to actually deactivate the free version.
The better solution for that would be to hook into the `admin_notices` hook and display the message within the WP admin interface.

Altogether, nothing to do with WPPD, but the EML plugin is buggy and could benefit from a complete code audit.

``` php
/**
 *  Temporary solution :: PRO only
 */
if ( ! function_exists( 'wpuxss_is_free_plugin_active' ) ) {
    add_action( 'admin_init', 'wpuxss_is_free_plugin_active' );

    function wpuxss_is_free_plugin_active() {
        if ( ! function_exists( 'get_plugins' ) ||
             ! function_exists( 'is_plugin_active' ) || 
             ! function_exists( 'deactivate_plugins' ) ) 
        {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
        }

        $all_plugins = get_plugins();
        $free_eml_plugin = 'enhanced-media-library/enhanced-media-library.php';

        if ( isset( $all_plugins[$free_eml_plugin] ) ) 
        {
            if ( version_compare( $all_plugins[$free_eml_plugin]['Version'], '2.0.4', '<' ) ) 
            {
                if ( is_plugin_active( $free_eml_plugin ) ) 
                {
                    deactivate_plugins( plugin_basename( __FILE__ ) );

                    wp_die( __('Please deactivate and <strong>remove</strong> the old FREE version prior to the <strong>Enhanced Media Library PRO</strong> activation. All your data will remain intact.', 'eml') . '<br /><br /><a href="' . admin_url( 'plugins.php' ) . '">&laquo; ' . __('Return to Plugins', 'eml') . '</a>' );
                } 
            }
        }
    }
}
```

**Comment by jerturowetz** [comment]
I'm really impressed you took the time to handle the issue despite it not being yours at all.  Very, very cool.

I'm going to copy the plugin maker on this thread - hopefully they'll give you some much-deserved props.

Thanks Juliette, pls be my mentor!

**Comment by jrfnl** [comment]
You're very welcome ;-) Let's hope the plugin maker fixes it.

Oh and if you're interested, I do believe you can still get tickets for the [plugin development best practices workshop](https://world.phparch.com/speakers/#34113) I'll be giving at PHPWorld in Washington next week ;-) Would be good to have you there, it's an awesome conference to attend.
